
/*
  Äldre representation av data som ger en bättre helhet tror jag.
*/

var SERVERdaysTest = [
    {"id": "801", "name": "lördag"},
  ];

const comp2018daysTest = [
    {"id": "lördag", "name": "lördag"},
    {"id": "söndag", "name": "söndag"},
];

const comp2019daysTest = [
    {"id": "fredag", "name": "fredag"},
    {"id": "lördag", "name": "lördag"},
    {"id": "söndag", "name": "söndag"},
];

var SERVERarenasTest = [
    {"id": "911", "name": "Löpning"},
    {"id": "912", "name": "LängdA"},
    {"id": "913", "name": "LängdB"},
    {"id": "914", "name": "HöjdA"},
    {"id": "915", "name": "HöjdB"},
    {"id": "916", "name": "Kula"},
];

const comp2018arenasTest = [
    {"id": "l", "name": "Löpning"},
    {"id": "k", "name": "Kula"},
    {"id": "v", "name": "Vikt"},
    {"id": "h", "name": "Höjd"},
    {"id": "ld", "name": "Längd"},
    {"id": "s", "name": "Stav"},
];

const comp2019arenasTest = [
    {"id": "löpning", "name": "Löpning"},
    {"id": "Kula", "name": "Kula"},
    {"id": "Kula 1", "name": "Kula 1"},
    {"id": "Kula 2", "name": "Kula 2"},
    {"id": "Slägga", "name": "Slägga"},
    {"id": "Höjd", "name": "Höjd"},
    {"id": "Längd 1", "name": "Längd 1"},
    {"id": "Längd 2", "name": "Längd 2"},
    {"id": "Tresteg", "name": "Tresteg"},
    {"id": "Stav", "name": "Stav"},
    {"id": "Spjut", "name": "Spjut"},
    {"id": "Diskus", "name": "Diskus"},
];

var comp2019eventsTest = [
{id: "KShöjd", day: "fredag", arena: "Höjd", starttime: "1020", duration: "90", class: "KS", gren: "höjd", grentype: "tech", preptime: 20},
{id: "KSslägga", day: "fredag", arena: "Slägga", starttime: "1020", duration: "45", class: "KS", gren: "slägga", grentype: "tech", preptime: 20},
{id: "KStresteg", day: "fredag", arena: "Tresteg", starttime: "1035", duration: "60", class: "KS", gren: "tresteg", grentype: "tech", preptime: 20},
{id: "MSkula", day: "fredag", arena: "Kula", starttime: "1035", duration: "20", class: "MS", gren: "kula", grentype: "tech", preptime: 20},
{id: "MS110mH", day: "fredag", arena: "löpning", starttime: "1065", duration: "10", class: "MS", gren: "110mH", grentype: "run", preptime: 0},
{id: "MSstav", day: "fredag", arena: "Stav", starttime: "1065", duration: "90", class: "MS", gren: "stav", grentype: "tech", preptime: 20},
{id: "P19110mH", day: "fredag", arena: "löpning", starttime: "1075", duration: "10", class: "P19", gren: "110", grentype: "run", preptime: 0},
{id: "P17110mH", day: "fredag", arena: "löpning", starttime: "1085", duration: "15", class: "P17", gren: "110", grentype: "run", preptime: 0},
{id: "KSkula", day: "fredag", arena: "Kula", starttime: "1090", duration: "20", class: "KS", gren: "kula", grentype: "tech", preptime: 20},
{id: "MSslägga", day: "fredag", arena: "Slägga", starttime: "1090", duration: "30", class: "MS", gren: "slägga", grentype: "tech", preptime: 20},
{id: "F19100mH", day: "fredag", arena: "löpning", starttime: "1100", duration: "5", class: "F19", gren: "100", grentype: "run", preptime: 0},
{id: "KS100mH", day: "fredag", arena: "löpning", starttime: "1105", duration: "10", class: "KS", gren: "100", grentype: "run", preptime: 0},
{id: "F17100mH", day: "fredag", arena: "löpning", starttime: "1115", duration: "10", class: "F17", gren: "100", grentype: "run", preptime: 0},
{id: "KS3000m", day: "fredag", arena: "löpning", starttime: "1125", duration: "20", class: "KS", gren: "3000m", grentype: "run", preptime: 0},
{id: "MShöjd", day: "fredag", arena: "Höjd", starttime: "1140", duration: "90", class: "MS", gren: "höjd", grentype: "tech", preptime: 20},
{id: "MS100m", day: "fredag", arena: "löpning", starttime: "1145", duration: "10", class: "MS", gren: "100", grentype: "run", preptime: 0},
{id: "KS100m", day: "fredag", arena: "löpning", starttime: "1155", duration: "20", class: "KS", gren: "100", grentype: "run", preptime: 0},
{id: "MStresteg", day: "fredag", arena: "Tresteg", starttime: "1160", duration: "60", class: "MS", gren: "tresteg", grentype: "tech", preptime: 20},
{id: "KSdiskus", day: "fredag", arena: "Diskus", starttime: "1160", duration: "30", class: "KS", gren: "diskus", grentype: "tech", preptime: 20},
{id: "MS3000m", day: "fredag", arena: "löpning", starttime: "1175", duration: "20", class: "MS", gren: "3000", grentype: "run", preptime: 0},
{id: "KS400m", day: "fredag", arena: "löpning", starttime: "1195", duration: "10", class: "KS", gren: "400", grentype: "run", preptime: 0},
{id: "MS400m", day: "fredag", arena: "löpning", starttime: "1205", duration: "20", class: "MS", gren: "400", grentype: "run", preptime: 0},
{id: "MSdiskus", day: "fredag", arena: "Diskus", starttime: "1210", duration: "30", class: "MS", gren: "diskus", grentype: "tech", preptime: 20},
{id: "MS100m Final", day: "fredag", arena: "löpning", starttime: "1225", duration: "5", class: "MS", gren: "100m Final", grentype: "run", preptime: 0},
{id: "KS100m Final", day: "fredag", arena: "löpning", starttime: "1230", duration: "5", class: "KS", gren: "100m ", grentype: "run", preptime: 0},
{id: "P1160m", day: "lördag", arena: "löpning", starttime: "540", duration: "12", class: "P11", gren: "60", grentype: "run", preptime: 0},
{id: "P14längd", day: "lördag", arena: "Längd 1", starttime: "540", duration: "55", class: "P14", gren: "längd", grentype: "tech", preptime: 20},
{id: "F15längd", day: "lördag", arena: "Längd 2", starttime: "540", duration: "90", class: "F15", gren: "längd", grentype: "tech", preptime: 20},
{id: "P12spjut", day: "lördag", arena: "Spjut", starttime: "540", duration: "70", class: "P12", gren: "spjut", grentype: "tech", preptime: 20},
{id: "P13kula", day: "lördag", arena: "Kula 2", starttime: "540", duration: "50", class: "P13", gren: "kula", grentype: "tech", preptime: 20},
{id: "P15diskus", day: "lördag", arena: "Diskus", starttime: "540", duration: "40", class: "P15", gren: "diskus", grentype: "tech", preptime: 20},
{id: "F1060m", day: "lördag", arena: "löpning", starttime: "552", duration: "9", class: "F10", gren: "60", grentype: "run", preptime: 0},
{id: "P11höjd", day: "lördag", arena: "Höjd", starttime: "560", duration: "100", class: "P11", gren: "höjd", grentype: "tech", preptime: 20},
{id: "F17stav", day: "lördag", arena: "Stav", starttime: "560", duration: "120", class: "F17", gren: "stav", grentype: "tech", preptime: 20},
{id: "P1060m", day: "lördag", arena: "löpning", starttime: "561", duration: "12", class: "P10", gren: "60", grentype: "run", preptime: 0},
{id: "F1160m", day: "lördag", arena: "löpning", starttime: "573", duration: "18", class: "F11", gren: "60", grentype: "run", preptime: 0},
{id: "F1360m", day: "lördag", arena: "löpning", starttime: "591", duration: "18", class: "F13", gren: "60", grentype: "run", preptime: 0},
{id: "F14diskus", day: "lördag", arena: "Diskus", starttime: "600", duration: "40", class: "F14", gren: "diskus", grentype: "tech", preptime: 20},
{id: "P1360m", day: "lördag", arena: "löpning", starttime: "609", duration: "9", class: "P13", gren: "60", grentype: "run", preptime: 0},
{id: "P19kula", day: "lördag", arena: "Kula 1", starttime: "610", duration: "25", class: "P19", gren: "kula", grentype: "tech", preptime: 20},
{id: "P1260m", day: "lördag", arena: "löpning", starttime: "618", duration: "15", class: "P12", gren: "60", grentype: "run", preptime: 0},
{id: "P15spjut", day: "lördag", arena: "Spjut", starttime: "630", duration: "40", class: "P15", gren: "spjut", grentype: "tech", preptime: 20},
{id: "F1260m", day: "lördag", arena: "löpning", starttime: "633", duration: "23", class: "F12", gren: "60", grentype: "run", preptime: 0},
{id: "KSlängd", day: "lördag", arena: "Längd 1", starttime: "635", duration: "52", class: "KS", gren: "längd", grentype: "tech", preptime: 20},
{id: "P17längd", day: "lördag", arena: "Längd 2", starttime: "650", duration: "60", class: "P17", gren: "längd", grentype: "tech", preptime: 20},
{id: "F1580m", day: "lördag", arena: "löpning", starttime: "656", duration: "20", class: "F15", gren: "80", grentype: "run", preptime: 0},
{id: "F12kula", day: "lördag", arena: "Kula 2", starttime: "660", duration: "60", class: "F12", gren: "kula", grentype: "tech", preptime: 20},
{id: "F17diskus", day: "lördag", arena: "Diskus", starttime: "660", duration: "50", class: "F17", gren: "diskus", grentype: "tech", preptime: 20},
{id: "F1480m", day: "lördag", arena: "löpning", starttime: "676", duration: "24", class: "F14", gren: "80", grentype: "run", preptime: 0},
{id: "P13höjd", day: "lördag", arena: "Höjd", starttime: "680", duration: "80", class: "P13", gren: "höjd", grentype: "tech", preptime: 20},
{id: "F13spjut", day: "lördag", arena: "Spjut", starttime: "690", duration: "70", class: "F13", gren: "spjut", grentype: "tech", preptime: 20},
{id: "P1480m", day: "lördag", arena: "löpning", starttime: "700", duration: "8", class: "P14", gren: "80", grentype: "run", preptime: 0},
{id: "P17stav", day: "lördag", arena: "Stav", starttime: "700", duration: "120", class: "P17", gren: "stav", grentype: "tech", preptime: 20},
{id: "F14kula", day: "lördag", arena: "Kula 1", starttime: "700", duration: "40", class: "F14", gren: "kula", grentype: "tech", preptime: 20},
{id: "P1580m", day: "lördag", arena: "löpning", starttime: "708", duration: "21", class: "P15", gren: "80", grentype: "run", preptime: 0},
{id: "P17100m", day: "lördag", arena: "löpning", starttime: "729", duration: "20", class: "P17", gren: "100", grentype: "run", preptime: 0},
{id: "P14diskus", day: "lördag", arena: "Diskus", starttime: "730", duration: "45", class: "P14", gren: "diskus", grentype: "tech", preptime: 20},
{id: "F17100m", day: "lördag", arena: "löpning", starttime: "749", duration: "16", class: "F17", gren: "100", grentype: "run", preptime: 0},
{id: "MSlängd", day: "lördag", arena: "Längd 1", starttime: "750", duration: "50", class: "MS", gren: "längd", grentype: "tech", preptime: 20},
{id: "P12kula", day: "lördag", arena: "Kula 2", starttime: "750", duration: "55", class: "P12", gren: "kula", grentype: "tech", preptime: 20},
{id: "P15längd", day: "lördag", arena: "Längd 2", starttime: "760", duration: "60", class: "P15", gren: "längd", grentype: "tech", preptime: 20},
{id: "F15kula", day: "lördag", arena: "Kula 1", starttime: "760", duration: "50", class: "F15", gren: "kula", grentype: "tech", preptime: 20},
{id: "P19100m", day: "lördag", arena: "löpning", starttime: "765", duration: "15", class: "P19", gren: "100", grentype: "run", preptime: 0},
{id: "P1360m Final", day: "lördag", arena: "löpning", starttime: "780", duration: "4", class: "P13", gren: "60m ", grentype: "run", preptime: 0},
{id: "F11höjd", day: "lördag", arena: "Höjd", starttime: "780", duration: "100", class: "F11", gren: "höjd", grentype: "tech", preptime: 20},
{id: "F1160m Final", day: "lördag", arena: "löpning", starttime: "784", duration: "4", class: "F11", gren: "60m ", grentype: "run", preptime: 0},
{id: "F1060m Final", day: "lördag", arena: "löpning", starttime: "788", duration: "4", class: "F10", gren: "60m ", grentype: "run", preptime: 0},
{id: "P1060m Final", day: "lördag", arena: "löpning", starttime: "792", duration: "4", class: "P10", gren: "60m ", grentype: "run", preptime: 0},
{id: "P13spjut", day: "lördag", arena: "Spjut", starttime: "795", duration: "45", class: "P13", gren: "spjut", grentype: "tech", preptime: 20},
{id: "F19/P19diskus", day: "lördag", arena: "Diskus", starttime: "795", duration: "40", class: "F19/P19", gren: "diskus", grentype: "tech", preptime: 20},
{id: "P1160m Final", day: "lördag", arena: "löpning", starttime: "796", duration: "4", class: "P11", gren: "60m ", grentype: "run", preptime: 0},
{id: "F1360m Final", day: "lördag", arena: "löpning", starttime: "800", duration: "4", class: "F13", gren: "60m ", grentype: "run", preptime: 0},
{id: "F1260m Final", day: "lördag", arena: "löpning", starttime: "804", duration: "4", class: "F12", gren: "60m ", grentype: "run", preptime: 0},
{id: "P1260m Final", day: "lördag", arena: "löpning", starttime: "808", duration: "9", class: "P12", gren: "60m ", grentype: "run", preptime: 0},
{id: "F1480m Final", day: "lördag", arena: "löpning", starttime: "817", duration: "5", class: "F14", gren: "80m ", grentype: "run", preptime: 0},
{id: "F13kula", day: "lördag", arena: "Kula 2", starttime: "820", duration: "60", class: "F13", gren: "kula", grentype: "tech", preptime: 20},
{id: "P1480m Final", day: "lördag", arena: "löpning", starttime: "822", duration: "5", class: "P14", gren: "80m ", grentype: "run", preptime: 0},
{id: "P1580m Final", day: "lördag", arena: "löpning", starttime: "827", duration: "5", class: "P15", gren: "80m ", grentype: "run", preptime: 0},
{id: "F1580m Final", day: "lördag", arena: "löpning", starttime: "832", duration: "10", class: "F15", gren: "80m ", grentype: "run", preptime: 0},
{id: "KSstav", day: "lördag", arena: "Stav", starttime: "840", duration: "90", class: "KS", gren: "stav", grentype: "tech", preptime: 20},
{id: "P15kula", day: "lördag", arena: "Kula 1", starttime: "840", duration: "40", class: "P15", gren: "kula", grentype: "tech", preptime: 20},
{id: "P17100m Final", day: "lördag", arena: "löpning", starttime: "842", duration: "5", class: "P17", gren: "100m ", grentype: "run", preptime: 0},
{id: "F17100m Final", day: "lördag", arena: "löpning", starttime: "847", duration: "5", class: "F17", gren: "100m ", grentype: "run", preptime: 0},
{id: "F14längd", day: "lördag", arena: "Längd 2", starttime: "850", duration: "102", class: "F14", gren: "längd", grentype: "tech", preptime: 20},
{id: "F19100m Försök Final", day: "lördag", arena: "löpning", starttime: "852", duration: "5", class: "F19", gren: "100m Försök ", grentype: "run", preptime: 0},
{id: "F15diskus", day: "lördag", arena: "Diskus", starttime: "855", duration: "40", class: "F15", gren: "diskus", grentype: "tech", preptime: 20},
{id: "P19100m Final", day: "lördag", arena: "löpning", starttime: "857", duration: "15", class: "P19", gren: "100m ", grentype: "run", preptime: 0},
{id: "F13600m", day: "lördag", arena: "löpning", starttime: "872", duration: "10", class: "F13", gren: "600", grentype: "run", preptime: 0},
{id: "F10600m", day: "lördag", arena: "löpning", starttime: "882", duration: "5", class: "F10", gren: "600", grentype: "run", preptime: 0},
{id: "F12600m", day: "lördag", arena: "löpning", starttime: "887", duration: "10", class: "F12", gren: "600", grentype: "run", preptime: 0},
{id: "P11600m", day: "lördag", arena: "löpning", starttime: "897", duration: "5", class: "P11", gren: "600", grentype: "run", preptime: 0},
{id: "F17längd", day: "lördag", arena: "Längd 1", starttime: "900", duration: "70", class: "F17", gren: "längd", grentype: "tech", preptime: 20},
{id: "P14kula", day: "lördag", arena: "Kula 1", starttime: "900", duration: "40", class: "P14", gren: "kula", grentype: "tech", preptime: 20},
{id: "P12600m", day: "lördag", arena: "löpning", starttime: "902", duration: "10", class: "P12", gren: "600", grentype: "run", preptime: 0},
{id: "P10600m", day: "lördag", arena: "löpning", starttime: "912", duration: "10", class: "P10", gren: "600", grentype: "run", preptime: 0},
{id: "P17diskus", day: "lördag", arena: "Diskus", starttime: "915", duration: "60", class: "P17", gren: "diskus", grentype: "tech", preptime: 20},
{id: "F13höjd", day: "lördag", arena: "Höjd", starttime: "920", duration: "100", class: "F13", gren: "höjd", grentype: "tech", preptime: 20},
{id: "F15spjut", day: "lördag", arena: "Spjut", starttime: "920", duration: "45", class: "F15", gren: "spjut", grentype: "tech", preptime: 20},
{id: "P13600m", day: "lördag", arena: "löpning", starttime: "922", duration: "5", class: "P13", gren: "600", grentype: "run", preptime: 0},
{id: "F11600m", day: "lördag", arena: "löpning", starttime: "927", duration: "20", class: "F11", gren: "600", grentype: "run", preptime: 0},
{id: "P15800m", day: "lördag", arena: "löpning", starttime: "947", duration: "10", class: "P15", gren: "800", grentype: "run", preptime: 0},
{id: "MS800m", day: "lördag", arena: "löpning", starttime: "957", duration: "20", class: "MS", gren: "800", grentype: "run", preptime: 0},
{id: "KS800m", day: "lördag", arena: "löpning", starttime: "977", duration: "10", class: "KS", gren: "800", grentype: "run", preptime: 0},
{id: "F15800m", day: "lördag", arena: "löpning", starttime: "987", duration: "5", class: "F15", gren: "800", grentype: "run", preptime: 0},
{id: "P14800m", day: "lördag", arena: "löpning", starttime: "992", duration: "5", class: "P14", gren: "800", grentype: "run", preptime: 0},
{id: "F14800m", day: "lördag", arena: "löpning", starttime: "997", duration: "15", class: "F14", gren: "800", grentype: "run", preptime: 0},
{id: "MS400mH", day: "lördag", arena: "löpning", starttime: "1012", duration: "10", class: "MS", gren: "400", grentype: "run", preptime: 0},
{id: "KS400mH", day: "lördag", arena: "löpning", starttime: "1022", duration: "15", class: "KS", gren: "400", grentype: "run", preptime: 0},
{id: "F17300mH", day: "lördag", arena: "löpning", starttime: "1037", duration: "10", class: "F17", gren: "300", grentype: "run", preptime: 0},
{id: "P17300mH", day: "lördag", arena: "löpning", starttime: "1047", duration: "10", class: "P17", gren: "300", grentype: "run", preptime: 0},
{id: "F11 heat1längd", day: "söndag", arena: "Längd 2", starttime: "540", duration: "45", class: "F11 heat1", gren: "längd", grentype: "tech", preptime: 20},
{id: "P14höjd", day: "söndag", arena: "Höjd", starttime: "540", duration: "70", class: "P14", gren: "höjd", grentype: "tech", preptime: 20},
{id: "F14spjut", day: "söndag", arena: "Spjut", starttime: "540", duration: "50", class: "F14", gren: "spjut", grentype: "tech", preptime: 20},
{id: "F17kula", day: "söndag", arena: "Kula", starttime: "540", duration: "60", class: "F17", gren: "kula", grentype: "tech", preptime: 20},
{id: "F1260mH", day: "söndag", arena: "löpning", starttime: "555", duration: "12", class: "F12", gren: "60", grentype: "run", preptime: 0},
{id: "P17slägga", day: "söndag", arena: "Slägga", starttime: "555", duration: "45", class: "P17", gren: "slägga", grentype: "tech", preptime: 20},
{id: "F1360mH", day: "söndag", arena: "löpning", starttime: "567", duration: "14", class: "F13", gren: "60", grentype: "run", preptime: 0},
{id: "P1260mH", day: "söndag", arena: "löpning", starttime: "581", duration: "9", class: "P12", gren: "60", grentype: "run", preptime: 0},
{id: "P1360mH", day: "söndag", arena: "löpning", starttime: "590", duration: "11", class: "P13", gren: "60", grentype: "run", preptime: 0},
{id: "F11 heat2längd", day: "söndag", arena: "Längd 2", starttime: "600", duration: "45", class: "F11 heat2", gren: "längd", grentype: "tech", preptime: 20},
{id: "F1580mH", day: "söndag", arena: "löpning", starttime: "601", duration: "12", class: "F15", gren: "80", grentype: "run", preptime: 0},
{id: "P13längd", day: "söndag", arena: "Längd 1", starttime: "605", duration: "45", class: "P13", gren: "längd", grentype: "tech", preptime: 20},
{id: "F1480mH", day: "söndag", arena: "löpning", starttime: "613", duration: "17", class: "F14", gren: "80", grentype: "run", preptime: 0},
{id: "F17spjut", day: "söndag", arena: "Spjut", starttime: "620", duration: "45", class: "F17", gren: "spjut", grentype: "tech", preptime: 20},
{id: "P10kula", day: "söndag", arena: "Kula", starttime: "620", duration: "45", class: "P10", gren: "kula", grentype: "tech", preptime: 20},
{id: "F19slägga", day: "söndag", arena: "Slägga", starttime: "620", duration: "30", class: "F19", gren: "slägga", grentype: "tech", preptime: 20},
{id: "P1580mH", day: "söndag", arena: "löpning", starttime: "630", duration: "18", class: "P15", gren: "80", grentype: "run", preptime: 0},
{id: "F15höjd", day: "söndag", arena: "Höjd", starttime: "630", duration: "70", class: "F15", gren: "höjd", grentype: "tech", preptime: 20},
{id: "P1480mH Försök Final", day: "söndag", arena: "löpning", starttime: "648", duration: "10", class: "P14", gren: "80mH Försök ", grentype: "run", preptime: 0},
{id: "F1280mH Final", day: "söndag", arena: "löpning", starttime: "658", duration: "5", class: "F12", gren: "80mH ", grentype: "run", preptime: 0},
{id: "F1360mH Final", day: "söndag", arena: "löpning", starttime: "663", duration: "10", class: "F13", gren: "60mH ", grentype: "run", preptime: 0},
{id: "F10längd", day: "söndag", arena: "Längd 1", starttime: "670", duration: "45", class: "F10", gren: "längd", grentype: "tech", preptime: 20},
{id: "F12 heat1längd", day: "söndag", arena: "Längd 2", starttime: "670", duration: "35", class: "F12 heat1", gren: "längd", grentype: "tech", preptime: 20},
{id: "P1260mH Final", day: "söndag", arena: "löpning", starttime: "673", duration: "5", class: "P12", gren: "60mH ", grentype: "run", preptime: 0},
{id: "P1360mH Final", day: "söndag", arena: "löpning", starttime: "678", duration: "10", class: "P13", gren: "60mH ", grentype: "run", preptime: 0},
{id: "P17kula", day: "söndag", arena: "Kula", starttime: "685", duration: "50", class: "P17", gren: "kula", grentype: "tech", preptime: 20},
{id: "F1480mH Final", day: "söndag", arena: "löpning", starttime: "688", duration: "20", class: "F14", gren: "80mH ", grentype: "run", preptime: 0},
{id: "F14slägga", day: "söndag", arena: "Slägga", starttime: "690", duration: "45", class: "F14", gren: "slägga", grentype: "tech", preptime: 20},
{id: "P14spjut", day: "söndag", arena: "Spjut", starttime: "700", duration: "45", class: "P14", gren: "spjut", grentype: "tech", preptime: 20},
{id: "F1580mH Final", day: "söndag", arena: "löpning", starttime: "708", duration: "5", class: "F15", gren: "80mH ", grentype: "run", preptime: 0},
{id: "P1580mH Final", day: "söndag", arena: "löpning", starttime: "713", duration: "10", class: "P15", gren: "80mH ", grentype: "run", preptime: 0},
{id: "F12 heat2längd", day: "söndag", arena: "Längd 2", starttime: "720", duration: "35", class: "F12 heat2", gren: "längd", grentype: "tech", preptime: 20},
{id: "KS1500m", day: "söndag", arena: "löpning", starttime: "723", duration: "14", class: "KS", gren: "1500", grentype: "run", preptime: 0},
{id: "MS1500m", day: "söndag", arena: "löpning", starttime: "737", duration: "14", class: "MS", gren: "1500", grentype: "run", preptime: 0},
{id: "P15300m", day: "söndag", arena: "löpning", starttime: "751", duration: "10", class: "P15", gren: "300", grentype: "run", preptime: 0},
{id: "F11kula", day: "söndag", arena: "Kula", starttime: "755", duration: "50", class: "F11", gren: "kula", grentype: "tech", preptime: 20},
{id: "F15slägga", day: "söndag", arena: "Slägga", starttime: "755", duration: "40", class: "F15", gren: "slägga", grentype: "tech", preptime: 20},
{id: "F14300m", day: "söndag", arena: "löpning", starttime: "761", duration: "20", class: "F14", gren: "300", grentype: "run", preptime: 0},
{id: "P15höjd", day: "söndag", arena: "Höjd", starttime: "770", duration: "100", class: "P15", gren: "höjd", grentype: "tech", preptime: 20},
{id: "P12längd", day: "söndag", arena: "Längd 1", starttime: "780", duration: "70", class: "P12", gren: "längd", grentype: "tech", preptime: 20},
{id: "P11längd", day: "söndag", arena: "Längd 2", starttime: "780", duration: "50", class: "P11", gren: "längd", grentype: "tech", preptime: 20},
{id: "F15300m", day: "söndag", arena: "löpning", starttime: "781", duration: "10", class: "F15", gren: "300", grentype: "run", preptime: 0},
{id: "P14300m", day: "söndag", arena: "löpning", starttime: "791", duration: "15", class: "P14", gren: "300", grentype: "run", preptime: 0},
{id: "F12spjut", day: "söndag", arena: "Spjut", starttime: "800", duration: "60", class: "F12", gren: "spjut", grentype: "tech", preptime: 20},
{id: "KS3000mH", day: "söndag", arena: "löpning", starttime: "806", duration: "20", class: "KS", gren: "3000", grentype: "run", preptime: 0},
{id: "F17slägga", day: "söndag", arena: "Slägga", starttime: "815", duration: "60", class: "F17", gren: "slägga", grentype: "tech", preptime: 20},
{id: "F10kula", day: "söndag", arena: "Kula", starttime: "825", duration: "40", class: "F10", gren: "kula", grentype: "tech", preptime: 20},
{id: "MS3000mH", day: "söndag", arena: "löpning", starttime: "826", duration: "20", class: "MS", gren: "3000", grentype: "run", preptime: 0},
{id: "F13200m", day: "söndag", arena: "löpning", starttime: "846", duration: "25", class: "F13", gren: "200", grentype: "run", preptime: 0},
{id: "P10längd", day: "söndag", arena: "Längd 2", starttime: "850", duration: "60", class: "P10", gren: "längd", grentype: "tech", preptime: 20},
{id: "P17spjut", day: "söndag", arena: "Spjut", starttime: "870", duration: "35", class: "P17", gren: "spjut", grentype: "tech", preptime: 20},
{id: "F17200m", day: "söndag", arena: "löpning", starttime: "871", duration: "20", class: "F17", gren: "200", grentype: "run", preptime: 0},
{id: "F13 heat1längd", day: "söndag", arena: "Längd 1", starttime: "880", duration: "50", class: "F13 heat1", gren: "längd", grentype: "tech", preptime: 20},
{id: "F14höjd", day: "söndag", arena: "Höjd", starttime: "880", duration: "110", class: "F14", gren: "höjd", grentype: "tech", preptime: 20},
{id: "P11kula", day: "söndag", arena: "Kula", starttime: "885", duration: "40", class: "P11", gren: "kula", grentype: "tech", preptime: 20},
{id: "P17200m", day: "söndag", arena: "löpning", starttime: "891", duration: "20", class: "P17", gren: "200", grentype: "run", preptime: 0},
{id: "P19slägga", day: "söndag", arena: "Slägga", starttime: "895", duration: "20", class: "P19", gren: "slägga", grentype: "tech", preptime: 20},
{id: "MS200m", day: "söndag", arena: "löpning", starttime: "911", duration: "15", class: "MS", gren: "200", grentype: "run", preptime: 0},
{id: "KS200m", day: "söndag", arena: "löpning", starttime: "926", duration: "15", class: "KS", gren: "200", grentype: "run", preptime: 0},
{id: "P14/P15slägga", day: "söndag", arena: "Slägga", starttime: "935", duration: "40", class: "P14/P15", gren: "slägga", grentype: "tech", preptime: 20},
{id: "F13 heat2längd", day: "söndag", arena: "Längd 1", starttime: "940", duration: "50", class: "F13 heat2", gren: "längd", grentype: "tech", preptime: 20},
{id: "F19200m", day: "söndag", arena: "löpning", starttime: "941", duration: "10", class: "F19", gren: "200", grentype: "run", preptime: 0},
{id: "P19200m", day: "söndag", arena: "löpning", starttime: "951", duration: "10", class: "P19", gren: "200", grentype: "run", preptime: 0},
{id: "P13200m", day: "söndag", arena: "löpning", starttime: "961", duration: "20", class: "P13", gren: "200", grentype: "run", preptime: 0},
{id: "F17400m", day: "söndag", arena: "löpning", starttime: "981", duration: "5", class: "F17", gren: "400", grentype: "run", preptime: 0},
{id: "P17400m", day: "söndag", arena: "löpning", starttime: "986", duration: "15", class: "P17", gren: "400", grentype: "run", preptime: 0},
];


var SERVEReventsTest = [
     {"id": "13", "day": "801","arena": "911", "starttime": 510, "duration": 25, "class": "P06", "gren": "60", grentype: "run", preptime: 0},
     {"id": "25", "day": "801","arena": "911", "starttime": 535, "duration": 25, "class": "F04", "gren": "60", grentype: "run", preptime: 0},
     {"id": "5", "day": "801","arena": "911", "starttime": 560, "duration": 15, "class": "P04", "gren": "60", grentype: "run", preptime: 0},
     {"id": "21", "day": "801","arena": "911", "starttime": 575, "duration": 15, "class": "F03", "gren": "60", grentype: "run", preptime: 0},
    {"id": "1", "day": "801","arena": "911", "starttime": 590, "duration": 10, "class": "P03", "gren": "60", grentype: "run", preptime: 0},
    {"id": "33", "day": "801","arena": "911", "starttime": 600, "duration": 20, "class": "F06", "gren": "60", grentype: "run", preptime: 0},
    {"id": "100", "day": "801","arena": "911", "starttime": 620, "duration": 5, "class": "P06", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "101", "day": "801","arena": "911", "starttime": 625, "duration": 5, "class": "P04", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "102", "day": "801","arena": "911", "starttime": 630, "duration": 5, "class": "F03", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "103", "day": "801","arena": "911", "starttime": 635, "duration": 5, "class": "P03", "gren": "60m ", grentype: "run", preptime: 0},
     {"id": "36", "day": "801","arena": "911", "starttime": 640, "duration": 30, "class": "F03", "gren": "60", grentype: "run", preptime: 0},
     {"id": "104", "day": "801","arena": "911", "starttime": 670, "duration": 5, "class": "F04", "gren": "60m ", grentype: "run", preptime: 0},
     {"id": "16", "day": "801","arena": "911", "starttime": 675, "duration": 30, "class": "P07 ", "gren": "60", grentype: "run", preptime: 0},
     {"id": "105", "day": "801","arena": "911", "starttime": 705, "duration": 5, "class": "F06", "gren": "60", grentype: "run", preptime: 0},
     {"id": "29", "day": "801","arena": "911", "starttime": 710, "duration": 30, "class": "F05", "gren": "60", grentype: "run", preptime: 0},
     {"id": "9", "day": "801","arena": "911", "starttime": 740, "duration": 20, "class": "P05", "gren": "60", grentype: "run", preptime: 0},
    {"id": "106", "day": "801","arena": "911", "starttime": 760, "duration": 5, "class": "F07", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "107", "day": "801","arena": "911", "starttime": 765, "duration": 5, "class": "P07", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "39", "day": "801","arena": "911", "starttime": 770, "duration": 20, "class": "F08", "gren": "60", grentype: "run", preptime: 0},
    {"id": "19", "day": "801","arena": "911", "starttime": 790, "duration": 20, "class": "P08", "gren": "60", grentype: "run", preptime: 0},
    {"id": "108", "day": "801","arena": "911", "starttime": 810, "duration": 5, "class": "F05", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "14", "day": "801","arena": "911", "starttime": 815, "duration": 25, "class": "P06", "gren": "600", grentype: "run", preptime: 0},
    {"id": "34", "day": "801","arena": "911", "starttime": 840, "duration": 20, "class": "F06", "gren": "600", grentype: "run", preptime: 0},
    {"id": "6", "day": "801","arena": "911", "starttime": 860, "duration": 10, "class": "P04", "gren": "600", grentype: "run", preptime: 0},
    {"id": "109", "day": "801","arena": "911", "starttime": 870, "duration": 5, "class": "P05", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "110", "day": "801","arena": "911", "starttime": 875, "duration": 5, "class": "F08", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "111", "day": "801","arena": "911", "starttime": 880, "duration": 5, "class": "P08", "gren": "60m ", grentype: "run", preptime: 0},
    {"id": "26", "day": "801","arena": "911", "starttime": 885, "duration": 20, "class": "F04", "gren": "600", grentype: "run", preptime: 0},
    {"id": "10", "day": "801","arena": "911", "starttime": 905, "duration": 20, "class": "P05", "gren": "600", grentype: "run", preptime: 0},
    {"id": "30", "day": "801","arena": "911", "starttime": 925, "duration": 25, "class": "F05", "gren": "600", grentype: "run", preptime: 0},
    {"id": "37", "day": "801","arena": "911", "starttime": 950, "duration": 20, "class": "F07", "gren": "400", grentype: "run", preptime: 0},
    {"id": "17", "day": "801","arena": "911", "starttime": 970, "duration": 30, "class": "P07", "gren": "400", grentype: "run", preptime: 0},
    {"id": "22", "day": "801","arena": "911", "starttime": 1000, "duration": 10, "class": "F03", "gren": "600", grentype: "run", preptime: 0},
    {"id": "2", "day": "801","arena": "911", "starttime": 1010, "duration": 5, "class": "P03", "gren": "600", grentype: "run", preptime: 0},

    {"id": "5633", "day": "801","arena": "912", "starttime": 550, "duration": 50, "class": "P06", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "5433", "day": "801","arena": "912", "starttime": 600, "duration": 50, "class": "F04", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "3233", "day": "801","arena": "912", "starttime": 650, "duration": 30, "class": "P04", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "6433", "day": "801","arena": "912", "starttime": 680, "duration": 60, "class": "F07", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "4533", "day": "801","arena": "912", "starttime": 760, "duration": 40, "class": "F06", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "7133", "day": "801","arena": "912", "starttime": 830, "duration": 65, "class": "P07", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "4433", "day": "801","arena": "912", "starttime": 910, "duration": 40, "class": "F08", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "5033", "day": "801","arena": "912", "starttime": 950, "duration": 45, "class": "P08", "gren": "Längd", grentype: "tech", preptime: 20},

    {"id": "5644", "day": "801","arena": "913", "starttime": 550, "duration": 50, "class": "P06", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "5444", "day": "801","arena": "913", "starttime": 600, "duration": 50, "class": "F04", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "3244", "day": "801","arena": "913", "starttime": 650, "duration": 30, "class": "P04", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "6444", "day": "801","arena": "913", "starttime": 680, "duration": 60, "class": "F07", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "4544", "day": "801","arena": "913", "starttime": 760, "duration": 40, "class": "F06", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "7144", "day": "801","arena": "913", "starttime": 830, "duration": 65, "class": "P07", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "4444", "day": "801","arena": "913", "starttime": 910, "duration": 40, "class": "F08", "gren": "Längd", grentype: "tech", preptime: 20},
    {"id": "5044", "day": "801","arena": "913", "starttime": 950, "duration": 45, "class": "P08", "gren": "Längd", grentype: "tech", preptime: 20},

    {"id": "31a", "day": "801","arena": "914", "starttime": 540, "duration": 105, "class": "F05", "gren": "Höjd", grentype: "tech", preptime: 20},
    {"id": "11a", "day": "801","arena": "914", "starttime": 650, "duration": 80, "class": "P05", "gren": "Höjd", grentype: "tech", preptime: 20},
    {"id": "3", "day": "801","arena": "914", "starttime": 740, "duration": 50, "class": "P03", "gren": "Höjd", grentype: "tech", preptime: 20},

    {"id": "31b", "day": "801","arena": "915", "starttime": 540, "duration": 105, "class": "F05", "gren": "Höjd", grentype: "tech", preptime: 20},
    {"id": "11b", "day": "801","arena": "915", "starttime": 650, "duration": 80, "class": "P05", "gren": "Höjd", grentype: "tech", preptime: 20},
    {"id": "23", "day": "801","arena": "915", "starttime": 740, "duration": 100, "class": "F03", "gren": "Höjd", grentype: "tech", preptime: 20},

    {"id": "8", "day": "801","arena": "916", "starttime": 585, "duration": 105, "class": "P04", "gren": "Kula", grentype: "tech", preptime: 20},
    {"id": "24", "day": "801","arena": "916", "starttime": 645, "duration": 80, "class": "F03", "gren": "Kula", grentype: "tech", preptime: 20},
    {"id": "28", "day": "801","arena": "916", "starttime": 695, "duration": 50, "class": "F04", "gren": "Kula", grentype: "tech", preptime: 20},
    {"id": "4", "day": "801","arena": "916", "starttime": 745, "duration": 25, "class": "P03", "gren": "Kula", grentype: "tech", preptime: 20},
    {"id": "12", "day": "801","arena": "916", "starttime": 775, "duration": 50, "class": "P05", "gren": "Kula", grentype: "tech", preptime: 20},
    {"id": "32", "day": "801","arena": "916", "starttime": 845, "duration": 80, "class": "F05", "gren": "Kula", grentype: "tech", preptime: 20},
];

const comp2018eventsTest = [
    {id: "P1160m", day: "lördag", arena: "l", starttime: "540", duration: "15", class: "P11", gren: "60", grentype: "run", preptime: 0},
    {id: "F11höjd", day: "lördag", arena: "h", starttime: "540", duration: "60", class: "F11", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "F12kula", day: "lördag", arena: "k", starttime: "540", duration: "60", class: "F12", gren: "kula", grentype: "tech", preptime: 20},
    {id: "F13längd", day: "lördag", arena: "ld", starttime: "550", duration: "45", class: "F13", gren: "längd", grentype: "tech", preptime: 20},
    {id: "F960m", day: "lördag", arena: "l", starttime: "555", duration: "15", class: "F9", gren: "60", grentype: "run", preptime: 0},
    {id: "P960m", day: "lördag", arena: "l", starttime: "570", duration: "21", class: "P9", gren: "60", grentype: "run", preptime: 0},
    {id: "F1560m", day: "lördag", arena: "l", starttime: "591", duration: "15", class: "F15", gren: "60", grentype: "run", preptime: 0},
    {id: "P1560m", day: "lördag", arena: "l", starttime: "606", duration: "9", class: "P15", gren: "60", grentype: "run", preptime: 0},
    {id: "F1160m", day: "lördag", arena: "l", starttime: "615", duration: "21", class: "F11", gren: "60", grentype: "run", preptime: 0},
    {id: "P13längd", day: "lördag", arena: "ld", starttime: "620", duration: "20", class: "P13", gren: "längd", grentype: "tech", preptime: 20},
    {id: "P11höjd", day: "lördag", arena: "h", starttime: "620", duration: "40", class: "P11", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "P860m", day: "lördag", arena: "l", starttime: "636", duration: "12", class: "P8", gren: "60", grentype: "run", preptime: 0},
    {id: "P12kula", day: "lördag", arena: "k", starttime: "640", duration: "45", class: "P12", gren: "kula", grentype: "tech", preptime: 20},
    {id: "F860m", day: "lördag", arena: "l", starttime: "648", duration: "12", class: "F8", gren: "60", grentype: "run", preptime: 0},
    {id: "F1260m", day: "lördag", arena: "l", starttime: "660", duration: "21", class: "F12", gren: "60", grentype: "run", preptime: 0},
    {id: "P9längd", day: "lördag", arena: "ld", starttime: "680", duration: "45", class: "P9", gren: "längd", grentype: "tech", preptime: 20},
    {id: "F1360m", day: "lördag", arena: "l", starttime: "681", duration: "24", class: "F13", gren: "60", grentype: "run", preptime: 0},
    {id: "P15höjd", day: "lördag", arena: "h", starttime: "700", duration: "40", class: "P15", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "P1360m", day: "lördag", arena: "l", starttime: "705", duration: "9", class: "P13", gren: "60", grentype: "run", preptime: 0},
    {id: "P1260m", day: "lördag", arena: "l", starttime: "714", duration: "15", class: "P12", gren: "60", grentype: "run", preptime: 0},
    {id: "F960m Final", day: "lördag", arena: "l", starttime: "729", duration: "5", class: "F9", gren: "60m ", grentype: "run", preptime: 0},
    {id: "F1560m Final", day: "lördag", arena: "l", starttime: "734", duration: "5", class: "F15", gren: "60m ", grentype: "run", preptime: 0},
    {id: "F860m Final", day: "lördag", arena: "l", starttime: "739", duration: "5", class: "F8", gren: "60m ", grentype: "run", preptime: 0},
    {id: "P860m Final", day: "lördag", arena: "l", starttime: "744", duration: "5", class: "P8", gren: "60m ", grentype: "run", preptime: 0},
    {id: "P960m Final", day: "lördag", arena: "l", starttime: "749", duration: "5", class: "P9", gren: "60m ", grentype: "run", preptime: 0},
    {id: "F9längd", day: "lördag", arena: "ld", starttime: "750", duration: "30", class: "F9", gren: "längd", grentype: "tech", preptime: 20},
    {id: "F15vikt", day: "lördag", arena: "v", starttime: "750", duration: "30", class: "F15", gren: "vikt", grentype: "tech", preptime: 20},
    {id: "F1160m Final", day: "lördag", arena: "l", starttime: "754", duration: "5", class: "F11", gren: "60m ", grentype: "run", preptime: 0},
    {id: "P1160m Final", day: "lördag", arena: "l", starttime: "759", duration: "5", class: "P11", gren: "60m ", grentype: "run", preptime: 0},
    {id: "F1260m Final", day: "lördag", arena: "l", starttime: "764", duration: "5", class: "F12", gren: "60m ", grentype: "run", preptime: 0},
    {id: "P1260m Final", day: "lördag", arena: "l", starttime: "769", duration: "5", class: "P12", gren: "60m ", grentype: "run", preptime: 0},
    {id: "F1360m Final", day: "lördag", arena: "l", starttime: "774", duration: "5", class: "F13", gren: "60m ", grentype: "run", preptime: 0},
    {id: "P1360m Final", day: "lördag", arena: "l", starttime: "779", duration: "5", class: "P13", gren: "60m ", grentype: "run", preptime: 0},
    {id: "P1560m Final", day: "lördag", arena: "l", starttime: "784", duration: "10", class: "P15", gren: "60m ", grentype: "run", preptime: 0},
    {id: "F9400m", day: "lördag", arena: "l", starttime: "794", duration: "24", class: "F9", gren: "400", grentype: "run", preptime: 0},
    {id: "F8längd", day: "lördag", arena: "ld", starttime: "800", duration: "35", class: "F8", gren: "längd", grentype: "tech", preptime: 20},
    {id: "P9400m", day: "lördag", arena: "l", starttime: "818", duration: "36", class: "P9", gren: "400", grentype: "run", preptime: 0},
    {id: "F15höjd", day: "lördag", arena: "h", starttime: "820", duration: "45", class: "F15", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "P15vikt", day: "lördag", arena: "v", starttime: "820", duration: "30", class: "P15", gren: "vikt", grentype: "tech", preptime: 20},
    {id: "F11600m", day: "lördag", arena: "l", starttime: "854", duration: "30", class: "F11", gren: "600", grentype: "run", preptime: 0},
    {id: "P8längd", day: "lördag", arena: "ld", starttime: "860", duration: "35", class: "P8", gren: "längd", grentype: "tech", preptime: 20},
    {id: "P11600m", day: "lördag", arena: "l", starttime: "884", duration: "18", class: "P11", gren: "600", grentype: "run", preptime: 0},
    {id: "F13600m", day: "lördag", arena: "l", starttime: "902", duration: "18", class: "F13", gren: "600", grentype: "run", preptime: 0},
    {id: "P13600m", day: "lördag", arena: "l", starttime: "920", duration: "18", class: "P13", gren: "600", grentype: "run", preptime: 0},
    {id: "P10höjd", day: "söndag", arena: "h", starttime: "540", duration: "60", class: "P10", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "F13kula", day: "söndag", arena: "k", starttime: "560", duration: "60", class: "F13", gren: "kula", grentype: "tech", preptime: 20},
    {id: "P15stav", day: "söndag", arena: "s", starttime: "560", duration: "150", class: "P15", gren: "stav", grentype: "tech", preptime: 20},
    {id: "F1040mH", day: "söndag", arena: "l", starttime: "570", duration: "24", class: "F10", gren: "40", grentype: "run", preptime: 0},
    {id: "P1040mH", day: "söndag", arena: "l", starttime: "594", duration: "29", class: "P10", gren: "40", grentype: "run", preptime: 0},
    {id: "F10höjd", day: "söndag", arena: "h", starttime: "620", duration: "70", class: "F10", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "P1160mH", day: "söndag", arena: "l", starttime: "623", duration: "9", class: "P11", gren: "60", grentype: "run", preptime: 0},
    {id: "F1160mH", day: "söndag", arena: "l", starttime: "632", duration: "12", class: "F11", gren: "60", grentype: "run", preptime: 0},
    {id: "F1260mH", day: "söndag", arena: "l", starttime: "644", duration: "15", class: "F12", gren: "60", grentype: "run", preptime: 0},
    {id: "F1360mH", day: "söndag", arena: "l", starttime: "659", duration: "17", class: "F13", gren: "60", grentype: "run", preptime: 0},
    {id: "P11kula", day: "söndag", arena: "k", starttime: "660", duration: "30", class: "P11", gren: "kula", grentype: "tech", preptime: 20},
    {id: "P1260mH", day: "söndag", arena: "l", starttime: "676", duration: "12", class: "P12", gren: "60", grentype: "run", preptime: 0},
    {id: "P1360mH", day: "söndag", arena: "l", starttime: "688", duration: "9", class: "P13", gren: "60", grentype: "run", preptime: 0},
    {id: "F1560mH", day: "söndag", arena: "l", starttime: "697", duration: "14", class: "F15", gren: "60", grentype: "run", preptime: 0},
    {id: "P12höjd", day: "söndag", arena: "h", starttime: "710", duration: "45", class: "P12", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "P1560mH", day: "söndag", arena: "l", starttime: "711", duration: "11", class: "P15", gren: "60", grentype: "run", preptime: 0},
    {id: "P1040mH Final", day: "söndag", arena: "l", starttime: "722", duration: "5", class: "P10", gren: "40mH ", grentype: "run", preptime: 0},
    {id: "F1040mH Final", day: "söndag", arena: "l", starttime: "727", duration: "10", class: "F10", gren: "40mH ", grentype: "run", preptime: 0},
    {id: "F1160mH Final", day: "söndag", arena: "l", starttime: "737", duration: "5", class: "F11", gren: "60mH ", grentype: "run", preptime: 0},
    {id: "F15stav", day: "söndag", arena: "s", starttime: "740", duration: "180", class: "F15", gren: "stav", grentype: "tech", preptime: 20},
    {id: "F1260mH Final", day: "söndag", arena: "l", starttime: "742", duration: "5", class: "F12", gren: "60mH ", grentype: "run", preptime: 0},
    {id: "F1360mH Final", day: "söndag", arena: "l", starttime: "747", duration: "5", class: "F13", gren: "60mH ", grentype: "run", preptime: 0},
    {id: "P1160mH Final", day: "söndag", arena: "l", starttime: "752", duration: "10", class: "P11", gren: "60mH ", grentype: "run", preptime: 0},
    {id: "P1360mH Final", day: "söndag", arena: "l", starttime: "762", duration: "5", class: "P13", gren: "60mH ", grentype: "run", preptime: 0},
    {id: "P1260mH Final", day: "söndag", arena: "l", starttime: "767", duration: "8", class: "P12", gren: "60mH ", grentype: "run", preptime: 0},
    {id: "F1560mH Final", day: "söndag", arena: "l", starttime: "775", duration: "10", class: "F15", gren: "60mH ", grentype: "run", preptime: 0},
    {id: "F12höjd", day: "söndag", arena: "h", starttime: "775", duration: "60", class: "F12", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "F11kula", day: "söndag", arena: "k", starttime: "775", duration: "25", class: "F11", gren: "kula", grentype: "tech", preptime: 20},
    {id: "P1560mH Final", day: "söndag", arena: "l", starttime: "785", duration: "10", class: "P15", gren: "60mH ", grentype: "run", preptime: 0},
    {id: "P12600m", day: "söndag", arena: "l", starttime: "795", duration: "18", class: "P12", gren: "600", grentype: "run", preptime: 0},
    {id: "P10600m", day: "söndag", arena: "l", starttime: "813", duration: "36", class: "P10", gren: "600", grentype: "run", preptime: 0},
    {id: "P13kula", day: "söndag", arena: "k", starttime: "830", duration: "30", class: "P13", gren: "kula", grentype: "tech", preptime: 20},
    {id: "F10600m", day: "söndag", arena: "l", starttime: "849", duration: "42", class: "F10", gren: "600", grentype: "run", preptime: 0},
    {id: "F13höjd", day: "söndag", arena: "h", starttime: "850", duration: "40", class: "F13", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "F12600m", day: "söndag", arena: "l", starttime: "891", duration: "24", class: "F12", gren: "600", grentype: "run", preptime: 0},
    {id: "P13höjd", day: "söndag", arena: "h", starttime: "910", duration: "45", class: "P13", gren: "höjd", grentype: "tech", preptime: 20},
    {id: "P15800m", day: "söndag", arena: "l", starttime: "915", duration: "18", class: "P15", gren: "800", grentype: "run", preptime: 0},
    {id: "F15800m", day: "söndag", arena: "l", starttime: "933", duration: "24", class: "F15", gren: "800", grentype: "run", preptime: 0}
];


/*
  Testdata for athleticsscheduler, SAYO Indoor 2017
*/
var SERVERcontestTest2017 = {
    "name": "SAYO Indoor 2017",
    "key": "test",
    "version": "1.0",
    "GLOBALID": 1000,
    "days": SERVERdaysTest,
    "arenas": SERVERarenasTest,
    "events": SERVEReventsTest,
};

/*
  Testdata for athleticsscheduler, SAYO Indoor 2018
*/
const comp2018 = {
  "name": "SAYO Indoor 2018",
  "key": "test",
  "version": "1.0",
  "GLOBALID": 2000,
  "days": comp2018daysTest,
  "arenas": comp2018arenasTest,
  "events": comp2018eventsTest,
}

/*
  Testdata for athleticsscheduler, SAYO Outdoor 2019
*/
const comp2019 = {
  "name": "SAYO Outdoor 2019",
  "key": "test",
  "version": "1.0",
  "days": comp2019daysTest,
  "arenas": comp2019arenasTest,
  "events": comp2019eventsTest,
}

//export const comptest = SERVERcontestTest2017;
export const comptest = comp2018;
export const localComps = [SERVERcontestTest2017, comp2018, comp2019];
